name: pose_tracker_linux_cuda
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.4
  - conda-forge::opencv>=4.9
  - conda-forge::pyyaml
  - conda-forge::loguru
  - conda-forge::rich
  - conda-forge::numpy<2
  - conda-forge::pyside6>=6.10
  - pip:
      - ultralytics>=8.2
      - lap
      - filterpy
      - pytest>=9.0
      - pandas
      - tensorflow[and-cuda]
      - scikit-learn
      - matplotlib
      - tf2onnx
      - onnxruntime-gpu